### ISSUE TITLE
address-picker

### ISSUE THREAD

**Issue by codewuguojie** [RoseEnd/address-picker#1]
你好，我使用了你的这个三级联动的组件，遇到了不能联动的问题，市区无法根据省的选择联动起来，不知道什么原因

**Comment by edison0951** [comment]
把this.slots[1].values = values[0].city改成picker.setSlotValues(1, values[0].city);
把this.slots[2].values = values[1].district改成picker.setSlotValues(2, values[1].district);

**Comment by RoseEnd** [comment]
已修正
